import com.example.trolls.R

class Dummy() {

    companion object{
        val youtuberToPosts: MutableMap<Youtuber, MutableList<Post>> = mutableMapOf()
        val youtubers: MutableList<Youtuber> = mutableListOf()
        val posts: MutableList<Post> = mutableListOf()
        val users: MutableList<User> = mutableListOf()
        val likes: MutableList<Like> = mutableListOf()
        val comments: MutableList<Comment> = mutableListOf()
    }

    init{

        //TODO: Intro 추가
        val jaeseon = User("yoo", "12345678","유재선", "jaeseon's nickname", profileImageResource = R.drawable.profile02)
        val jiwon = User("shin", "12345678","신지원", "jiwon's nickname", profileImageResource = R.drawable.profile04)
        val mun = User("jeon", "12345678","전문기", "munki's nickname", profileImageResource = R.drawable.profile03)
        val rian = User("kim", "12345678","김리안", "rian's nickname", profileImageResource = R.drawable.profile01)
        val seungmo = User("seong", "12345678","성승모", "seungmo's nickname", profileImageResource = R.drawable.profile05)

//        users = mutableListOf(jaeseon, jiwon, moonki, rian, seungmo)
        users.add(jaeseon)
        users.add(jiwon)
        users.add(mun)
        users.add(rian)
        users.add(seungmo)

        val comment1_1 = Comment("댓글입니다1_1", jaeseon)
        val comment1_2 = Comment("댓글입니다1_2", jaeseon)
        val comment1_3 = Comment("댓글입니다1_3", jaeseon)
        val comment2_1 = Comment("댓글입니다2_1", jiwon)
        val comment2_2 = Comment("댓글입니다2_2", jiwon)
        val comment2_3 = Comment("댓글입니다2_3", jiwon)
        val comment3_1 = Comment("댓글입니다3_1", mun)
        val comment3_2 = Comment("댓글입니다3_2", mun)
        val comment3_3 = Comment("댓글입니다3_3", mun)
        val comment4_1 = Comment("댓글입니다4_1", seungmo)
        val comment4_2 = Comment("댓글입니다4_2", seungmo)
        val comment4_3 = Comment("댓글입니다4_3", seungmo)
        val comment5_1 = Comment("댓글입니다5_1", rian)
        val comment5_2 = Comment("댓글입니다5_2", rian)
        val comment5_3 = Comment("댓글입니다5_3", rian)

        val like1_1 = Like(jaeseon)
        val like1_2 = Like(jiwon)
        val like1_3 = Like(mun)
        val like2_1 = Like(jaeseon)
        val like2_2 = Like(jiwon)
        val like2_3 = Like(mun)
        val like3_1 = Like(mun)
        val like3_2 = Like(seungmo)
        val like3_3 = Like(rian)
        val like4_1 = Like(seungmo)
        val like4_2 = Like(rian)
        val like4_3 = Like(mun)
        val like5_1 = Like(rian)
        val like5_2 = Like(mun)
        val like5_3 = Like(jiwon)


        val panni = Youtuber("panni", "1234", "빠니보틀", "panni", profileIcon = R.drawable.panni_bottle_profile_image)
        val kwack = Youtuber("kwack", "1234", "곽튜브", "kwack",profileIcon = R.drawable.kwack_profile_image)
        val wonji = Youtuber("wonji", "1234", "원지", "wonji", profileIcon = R.drawable.wonji_profile_image)
        val soy = Youtuber("soy", "1234", "쏘이", "soy", profileIcon = R.drawable.soy_profile_image)

        val post_panni1 = Post(R.drawable.post_main_image_panni1, "빠니보틀 제목1","본명 박재한. 1987년생. 현재 207만 명 구독자를 보유한 여행 유튜버로 현재 대한민국 여행 유튜버 구독자 수 1위다. 오지 탐험, 전쟁 폐허 탐방 등 그야말로 살아있는 여행 이야기를 전한다. 2015년 3월부터 여행 관련 영상을 올렸으며 웹드라마 <좋좋소>, <찐따록: 인간 곽준빈>의 연출, 극본을 맡아 PD로 활동하기도 했다.", jaeseon, panni, likes = mutableListOf(Like(jaeseon)), comments = mutableListOf(comment5_1))
        val post_panni2 = Post(R.drawable.post_main_image_panni2, "빠니보틀 제목2","빠니보틀이 여행은 자유롭다. 근데 특별하다. 기존에 TV에서 보던 여행 콘텐츠와는 확연하게 다르다. 남들이 가지 않은 곳, 알려지지 않은 곳을 여행하고 현지인과도 자연스럽게 소통하고 녹아든다. 빠니보틀 영상 중에 가장 유명한 건 ‘인도 기차 1등칸과 꼴등칸 비교체험’이다. 4년 전 영상이고 무려 753만 회 조회수를 기록 중이다.", jaeseon, panni)
        val post_panni3 = Post(R.drawable.post_main_image_panni3, "빠니보틀 제목3","여행 유튜브 채널은 많다. 그럼에도 빠니보틀 콘텐츠를 보는 이유가 있다. 색깔이 뚜렷하다. 대부분 브이로그나 여행지를 보여주며 설명하는 콘텐츠라면 빠니보틀 영상은 직접 여행하는 느낌이 든다. ", jaeseon, panni)
        val post_panni4 = Post(R.drawable.post_main_image_panni4, "빠니보틀 제목4","MBC <태어난 김에 세계일주> 시리즈에 빠니보틀이 합류하면서 분위기가 확 바뀌었다. 그가 합류하기 전까지는 기존 여행 예능에 가까웠는데 그 틀을 깨버린 것이다. 기안84의 영어 표현을 고쳐주거나 돈을 펑펑 쓰는 지갑을 압수하는 등 인간적인 모습은 물론 재미있는 장면도 많이 나왔다.", jiwon, panni)
        val post_panni5 = Post(R.drawable.post_main_image_panni5, "빠니보틀 제목5","항상 긍정적이다. 배려하는 행동도 몸에 배어있다. 페루 지역에서 노트북 가방을 도둑맞은 적이 있다. 150만 원가량의 돈과 카드, 노트북, 영상 파일, 외장하드, 각종 문서를 잃어버렸음에도 불구하고 빠니보틀은 메인 가방은 도난당하지 않았다며 웃었다. 에너지가 좋다. 모두가 빠니보틀에 스며들 수밖에 없다.", jiwon, panni)
        val post_panni6 = Post(R.drawable.post_main_image_panni6, "빠니보틀 제목6","빠니보틀은 1987년생으로 강원도 춘천에서 태어났다. 원래부터 자유분방한 성격에 여행을 좋아했다. 2007년 일본, 2009년 유럽, 2014년 남미를 자전거로 여행했으며, 2017년에는 동남아시아, 인도로 배낭여행을 떠났다. 그때 찍은 짤막한 영상들을 유튜브에 올리기도 했다. 프리랜서 생활을 하다가 잠시 디자인 회사에서 인턴 생활을 하기도 했다. 하지만 성격과 맞지 않는 보수적인 직장 환경에 일할 의욕이 나지 않았다. 결국 인턴 기간이 끝나자 백수가 됐다.", jiwon, panni)
        val post_kwack1 = Post(R.drawable.post_main_image_kwack1, "곽튜브 제목1","곽튜브보다 인간 곽준빈을 소개하고 싶었다. 유튜버로서 알게 모르게 여행하며 부담이 있었을텐데, 세계기사식당에선 마음 편하게 여행하고 인간적인 곽준빈 모습이 보였으면 했다. 현지에서도 곽튜브가 아니라 곽준빈으로 바라보지 않느냐. ", mun, kwack)
        val post_kwack2 = Post(R.drawable.post_main_image_kwack2, "곽튜브 제목2","곽준빈이 홍콩, 태국, 일본, 키르기스스탄 등 해외 기사식당을 방문하는 여행기다. 송 PD는 자이언트 펭TV에서 제작 PD를 맡았고, 이번이 첫 연출작이다. 콘텐츠진흥원 지원 사업에 선정됐을 때는 우려의 시선이 적지 않았다. 전형적인 EBS 프로그램이 아닌 만큼 내부 시사회에서도 반응이 엇갈렸다.", mun, kwack)
        val post_kwack3 = Post(R.drawable.post_main_image_kwack3, "곽튜브 제목3","곽튜브를 통해 세계인들이 어떻게 사는지 엿볼 수 있다. 집값이 올라서 고통 받거나 사업이 망해서 힘들어하고, 딸 자랑을 하거나 연애 고민을 털어놓는 등 우리네 모습과 별반 다르지 않다. \"교육방송(EBS)에서 펭수를 만들었지만, 가치와 감동을 줘 많은 사람들의 사랑을 받았다. 꼭 정보를 제공해야 교육이 되는 건 아니\"라며 \"공영방송이 사회적으로 해야 하는 중요한 역할\"이라고 설명했다.", jaeseon, kwack)
        val post_kwack4 = Post(R.drawable.post_main_image_kwack4, "곽튜브 제목4","신선한 아이템과 나라별 생활습관을 엮었다며 \"원래 물가 탐구를 고민했는데, 전면에 걸지 않고 자연스럽게  풀었다\"고 짚었다. \"홍콩에선 숙소를 빈관으로 잡았다. 한국 여관 같은 곳인데, 아파트와 게스트하우스가 같이 있다\"며 \"중앙아시아에선 고려인들을 만났다. ", mun, kwack)
        val post_kwack5 = Post(R.drawable.post_main_image_kwack5, "곽튜브 제목5","2회 홍콩편이 가장 기억에 남는다고 꼽았다. \"기사님이 투잡해서 길을 잘 몰랐다. 택시를 시작한 지 얼마 안 돼 10분 정도 걸리는 거리가 몇 시간 걸렸다. 그렇게 시키려고 해도 못할 것\"이라며 \"결국 준빈씨가 내비게이션을 보고 길을 알려줬다\"고 회상했다. \"태국은 택시가 거의 없고 그랩하는 분들이 많다. 그랩 기사들은 대부분 초보다.", mun, kwack)
        val post_kwack6 = Post(R.drawable.post_main_image_kwack6, "곽튜브 제목6","곽튜브 하면 '먹방'을 빼놓을 수 없다. 유튜브 채널에선 다이어트 선언을 한 뒤 점점 먹방으로 바뀌어 웃음을 주곤 했다. \"먹방은 꽤 중요한 콘텐츠\"라며 \"준빈씨가 워낙 음식을 안 가리고 잘 먹는다. 세계기사식당에선 화려하거나 비싸지 않고, tvN '스트리트 푸드 파이터'처럼 길거리 음식을 주로 먹는다.", rian, kwack)
        val post_wonji1 = Post(R.drawable.post_main_image_wonji1, "원지 제목1","원지는 “몇 년 동안 세계를 여행하면서 느낀 점은, 사람을 지탱하는 건 일상이고, 사람을 나아가게 하는 건 새로움이라는 것”이라고 말한다.", rian, wonji)
        val post_wonji2 = Post(R.drawable.post_main_image_wonji2, "원지 제목2","원지는 한곳에 오래 머무르는 느린 여행을 선호한다. 가장 인기 있는 영상은 조회 수 364만을 기록한 ‘미국 슬리핑 기차에서 보낸 놀라운 34시간’이다.", rian, wonji)
        val post_wonji3 = Post(R.drawable.post_main_image_wonji3, "원지 제목3","원지는 여행에서 특별한 계획 없이 즉흥적으로 하고 싶은 일을 하는 편이라 미용실이나 메이크업 숍을 다녀와 후기를 전하기도. 멕시코에서는 펌과 메이크업을 동시에 받은 뒤 “펌이 잘 나왔다. 결과에 만족한다. 그런데 약이 독해서 얼굴이 따가웠다. 메이크업은 섬세하다”고 평했다.", jaeseon, wonji)
        val post_wonji4 = Post(R.drawable.post_main_image_wonji4, "원지 제목4","원지는 한 인터뷰에서 “영상 중 일본 여행기 중 ‘태풍이 덮친 일본에 가면 생기는 일’과 에티오피아 여행 중 ‘사상 최악의 공항 체험기’가 제일 기억에 남는다”라고 밝힌 바 있다.", rian, wonji)
        val post_wonji5 = Post(R.drawable.post_main_image_wonji5, "원지 제목5","미국 LA의 한 회사에서 영상 제작 일을 하다가 한국으로 돌아온 원지는 영주권을 취득해 2022년 미국으로 떠났다.", rian, wonji)
        val post_wonji6 = Post(R.drawable.post_main_image_wonji6, "원지 제목6","원지가 자주 하는 말 중 하나는 “자본주의 만만세”다. 금액을 지불한 만큼 대가를 받을 수 있는 자본주의에서 공평함을 느낀다는 것. ‘자본주의의 나라’로 통하는 미국이기에 만족감을 느낀다고.ㅇ", seungmo, wonji)
        val post_soy1 = Post(R.drawable.post_main_image_soy1, "쏘이 제목1","‘여행 다니며 돈을 버는 인생이라니, 얼마나 행복할까?’ 현생에 치이고 집으로 돌아가는 버스 안. 새로 업로드된 여행 영상을 보며 멋모르는 생각을 한다. 마음 한편에 오래도록 자리 잡고 있는 세계일주의 꿈을 이룰 날을 기대하며 설렘 반, 부러움 반의 마음으로 여행 유튜버 이소연님을 만나보았다.", seungmo, soy)
        val post_soy2 = Post(R.drawable.post_main_image_soy2, "쏘이 제목2","전 세계를 격리시킨 코로나 사태는 온라인 세상에서 또 다른 기회가 됐다. 온라인상에서 간접적으로 체험하는 여행을 뜻하는 소위 ‘랜선 여행’의 전성기를 열어젖힌 것이다. 유튜브도 여기에 큰 몫을 했다. 수많은 사람이 카메라를 켜고 여행지 곳곳을 누비기 시작했다.\n", seungmo, soy)
        val post_soy3 = Post(R.drawable.post_main_image_soy3, "쏘이 제목3","유튜버 쏘이(본명 이소연)는 험난한 여행 유튜버의 세계에서 자신만의 입지를 다진 몇 안 되는 사람 중 한 명이다. 그의 채널 구독자 수는 10월 기준 53만8000명. SNS 빅데이터 분석 서비스 녹스인플루언서에 따르면 쏘이 채널은 구독자 기준으로 30위권이다. EBS 등 지상파 방송 채널을 제외하면 20위 안이다.", seungmo, soy)
        val post_soy4 = Post(R.drawable.post_main_image_soy4, "쏘이 제목4","쏘이가 2018년 초 여행 유튜버 세계에 뛰어든 후로 지금까지 여행한 나라는 40개국이 넘는다. 여자 혼자 떠나는 세계여행은 아무래도 치안상 위험이 많이 따를 수밖에 없다. 그럼에도 쏘이는 특유의 친화력과 긍정적인 성격으로 매 순간 위험을 극복해 나간다는 평이 자자하다.", seungmo, soy)
        val post_soy5 = Post(R.drawable.post_main_image_soy5, "쏘이 제목5","그는 23세에 공인노무사 시험에 합격한 바 있다. 안정적인 미래를 원했다면 충분히 실현할 수 있는 밑바탕을 갖췄다고 볼 수 있다. 하지만 쏘이는 여행지의 비포장도로만큼 굴곡지고 예측하기 힘든 현실을 택했다.\n", jaeseon, soy)
        val post_soy6 = Post(R.drawable.post_main_image_soy6, "쏘이 제목6","독창적 콘텐츠를 위해 험지로 나섰다가 봉변을 당한 경우도 적지 않다. 지난 4월에는 영국의 유명 유튜버가 카메라를 켜고 아프가니스탄을 누비다 탈레반에 의해 억류되기도 했다.\n", jaeseon, soy)

        posts.add(post_panni1)
        posts.add(post_wonji3)
        posts.add(post_soy2)
        posts.add(post_panni2)
        posts.add(post_kwack2)
        posts.add(post_panni6)
        posts.add(post_soy4)
        posts.add(post_panni3)
        posts.add(post_panni4)
        posts.add(post_soy6)
        posts.add(post_wonji5)
        posts.add(post_kwack3)
        posts.add(post_panni5)
        posts.add(post_kwack1)
        posts.add(post_soy3)
        posts.add(post_kwack4)
        posts.add(post_wonji4)
        posts.add(post_kwack5)
        posts.add(post_wonji1)
        posts.add(post_kwack6)
        posts.add(post_kwack2)
        posts.add(post_soy1)
        posts.add(post_wonji2)
        posts.add(post_wonji6)
        posts.add(post_soy5)

        likes.add(like1_1)
        likes.add(like1_2)
        likes.add(like1_3)
        likes.add(like2_1)
        likes.add(like2_2)
        likes.add(like2_3)
        likes.add(like3_1)
        likes.add(like3_2)
        likes.add(like3_3)
        likes.add(like4_1)
        likes.add(like4_2)
        likes.add(like4_3)
        likes.add(like5_1)
        likes.add(like5_2)
        likes.add(like5_3)

        comments.add(comment1_1)
        comments.add(comment1_2)
        comments.add(comment1_3)
        comments.add(comment2_1)
        comments.add(comment2_2)
        comments.add(comment2_3)
        comments.add(comment3_1)
        comments.add(comment3_2)
        comments.add(comment3_3)
        comments.add(comment4_1)
        comments.add(comment4_2)
        comments.add(comment4_3)
        comments.add(comment5_1)
        comments.add(comment5_2)
        comments.add(comment5_3)


        youtuberToPosts[panni] = mutableListOf(post_panni1, post_panni2,post_panni3,post_panni4,post_panni5,post_panni6)
        youtuberToPosts[kwack] = mutableListOf(post_kwack1, post_kwack2, post_kwack3, post_kwack4, post_kwack5, post_kwack6)
        youtuberToPosts[wonji] = mutableListOf(post_wonji1, post_wonji2, post_wonji3, post_wonji4, post_wonji5, post_wonji6)
        youtuberToPosts[soy] = mutableListOf(post_soy1, post_soy2, post_soy3, post_soy4, post_soy5, post_soy6)

        youtubers.add(panni)
        youtubers.add(kwack)
        youtubers.add(wonji)
        youtubers.add(soy)
    }

}